# -*- coding: utf-8 -*-
# @Time    : 2018/1/4 17:02
# @Author  : wangzhigang@tigerbrokers.com
# @FileName: main.yml
---
# Used only for Redhat installation, enables source Nginx repo.
nginx_yum_repo_enabled: true

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: false
nginx_ppa_version: stable

# 安装包名
nginx_package_name: "nginx"

# 暂无
nginx_conf_template: "nginxconf.j2"
nginx_proxy_template: "proxyhost.j2"

nginx_worker_processes: "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "102400"
nginx_multi_accept: "on"

nginx_error_log: "/usr/local/nginx/logs/error.log warn"
nginx_access_log: "/usr/local/nginx/logs/access.log main buffer=16k flush=2m"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
#nginx_keepalive_requests: "100"

#nginx_server_tokens: "on"

nginx_client_max_body_size: "50m"

nginx_server_names_hash_bucket_size: "128"

#nginx_proxy_cache_path: ""

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

nginx_remove_default_vhost: false
#nginx_vhosts:
## Example vhost below, showing all available options:
#  listen: "80" # default: "80"
#  server_name: "dev.itiger.com" # default: N/A
#  ssl_name: "itiger.com"
##  root: "" # default: N/A
#  index: "index.html index.htm" # default: "index.html index.htm"
#  filename: "dev.itiger.com.conf" # Can be used to set the filename of the vhost file.
#
#  # Properties that are only added if defined:
#  server_name_redirect: "dev.itiger.com" # default: N/A
#  error_page: ""
#  access_log: "/data0/logs/nginx/dev.itiger.com.access.log main"
#  error_log: "/data0/logs/nginx/dev.itiger.com.error.log error"
#  http_extra_parameters: true
#
#  template: "" # Can be used to override the `nginx_vhost_template` per host.
#  state: "absent" # To remove the vhost configuration.
#
#nginx_upstreams:
#  - name: "{{ nginx_upstream_name_80 }}"
#    strategy: "{{ nginx_upstream_strategy }}" # "least_conn", etc.
##   keepalive: 16 # optional
##   servers: "{{ backend_server_list }}" # 字符串列表，例子如下
##   servers: "{{ backend_server_list }}" # 字符串列表，例子如下
#    servers: {
#      "172.28.48.88",
#      "172.28.48.89 weight=3",
#      "172.28.48.90"
#    }
#  - name: "{{ nginx_upstream_name_443 }}"
#    strategy: "{{ nginx_upstream_strategy }}" # "least_conn", etc.
##   keepalive: 16 # optional
##   servers: "{{ backend_server_list }}" # 字符串列表，例子如下
##   servers: "{{ backend_server_list }}" # 字符串列表，例子如下
#    servers: {
#      "172.28.48.88",
#      "172.28.48.89 weight=3",
#      "172.28.48.90"
#    }

nginx_log_format: |
  '$remote_addr||$http_x_forwarded_for||$geoip_country_code||$geoip_city||$time_local'
  '||$server_name||$request||$request_length||$request_time||$uid_set||$uid_got'
  '||$status||$body_bytes_sent||$bytes_sent||$connection||$connection_requests'
  '||$http_user_agent||$http_referer||$upstream_addr||$upstream_status||$upstream_response_time';