# -*- coding: utf-8 -*-
# @Time    : 2018/1/4 16:57
# @Author  : wangzhigang@tigerbrokers.com
# @FileName: setup-RedHat.yml
---
- name: Enable nginx repo
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  when: nginx_yum_repo_enabled
  notify: yum makecache

- name: Ensure nginx is installed.
  yum:
    name: "{{ nginx_package_name }}"
    state: installed

- name: yum make cache
  gather_facts: False
  become_user: root
  become: yes
  become_method: sudo
  shell: yum makecache